### ISSUE TITLE
credentials tab remain in grey- cannot add credentials

### ISSUE THREAD

**Issue by Leoncoper** [NetAppDocs/bluexp-setup-admin#209]
### Page URL

https://docs.netapp.com/us-en/bluexp-setup-admin/task-install-private-mode.html

### Page title

Deploy the Connector in private mode

### Summary

in a new installation with connector on premise vm in private mode, it is not possible to add azure  credentials because credentials tab remains grey .it is not possibile to add credentials
the connector was installed on a virtual machine linux red hat 8.6 with offline package.
what we can check to able adding credentials, we need to reinstall connector ?
we cannot proceed to add credentals.
thanks

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-bcammett** [comment]
Hi @Leoncoper,

Red Hat Enterprise Linux 8.6 isn't supported. I would assume that's why you're having problems with the Connector. You can find the list of supporting operating systems on the following page:
https://docs.netapp.com/us-en/bluexp-setup-admin/task-prepare-private-mode.html

If you continue to have issues, it's best to reach out to NetApp Support through the BlueXP in-product chat or by phone:
https://www.netapp.com/company/contact-us/support/#technical_support

Regards,
Ben

**Comment by Leoncoper** [comment]
really? I have checked some days ago netapp documentation page and 8.6 and 8.7 were supported, i saved also the netapp page.
I'm going to deploy a new virtual machine with red hat 7.9 now.

**Comment by netapp-bcammett** [comment]
Yes, support for RHEL 8.6 and 8.7 were removed on 7 May.
https://docs.netapp.com/us-en/bluexp-setup-admin/whats-new.html#7-may-2023
