### ISSUE TITLE
Domain users support

### ISSUE THREAD

**Issue by anee04** [NetAppDocs/bluexp-setup-admin#275]
### Page URL

https://docs.netapp.com/us-en/bluexp-setup-admin/task-configuring-proxy.html

### Page title

Configure a Connector to use a proxy server

### Summary

Hello Ben,

1. To change : Earlier there was a doc request raised to mention that Domain users fails due to username field having domain**\**username and REST API failed. The below must be changed as it works now with a workaround 

**The user must be a local user. Domain users are not supported.**

It works now with workaround as below :
domain**%92**username

2. To Add: If passwords have special characters, then again we need to use the same ASCII codes for each special character for REST APIs to work.

Example Password: NetApp# should be provided as NetApp%35 etc.

We can provide an assisting link such as https://theasciicode.com.ar/

I'll copy you on an e-mail thread that is related to the same.

Also on previous github ticket remember changing domain user support for proxy in various places and need to address every link.

Thanks

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by anee04** [comment]
https://github.com/NetAppDocs/bluexp-copy-sync/issues/55

old ticket above earlier requesting the format of domain user name for proxy on multiple links and it needs to be corrected everywhere as well.

**Comment by netapp-bcammett** [comment]
Thank you, Anee. I'll get started on the doc updates soon and reach out if I have any questions.

Regards,
Ben

**Comment by netapp-bcammett** [comment]
I updated the Connector documentation to remove the limitation that states domain users are not supported when setting up a proxy server (see https://github.com/NetAppDocs/bluexp-setup-admin/pull/277).

I suggest opening new issues after testing is complete for the other scenarios so that we have complete details to proceed with additional doc updates: passwords with special characters and domain users with BlueXP copy and sync and with BlueXP classification.
