### ISSUE TITLE
API Endpoint Ambiguity - Restricted Mode

### ISSUE THREAD

**Issue by jefft8910** [NetAppDocs/bluexp-setup-admin#292]
### Page URL

https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html

### Page title

Learn about BlueXP deployment modes

### Summary

The comparison table for standard/restricted/private modes says that API endpoint is "The BlueXP SaaS layer" - I believe this should be the connector, similar to UI access.  Ultimately the BXP SaaS layer cannot control deploying and managing CVO via automation in restricted mode.

If I'm misunderstanding API endpoint's meaning, perhaps it needs to be clarified.

Thanks!

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-tonacki** [comment]
Hi [jefft8910](https://github.com/jefft8910),  I think both standard and restricted use the API endpoint https://cloudmanager.cloud.netapp.com, but I am not the expert on this documentation content.  I have assigned this to Ben and he'll take a look when he gets back to the office.

Thanks, Tom

**Comment by netapp-bcammett** [comment]
@jefft8910, thank you for reaching out. I believe you are correct in your assessment, but I'm waiting for final validation from the product team before making the update.

Note that this issue was already reported in https://github.com/NetAppDocs/bluexp-setup-admin/issues/273 so I'm going to go ahead and close this one. But you can track the referenced issue for updates.

Thanks again,
Ben
