### ISSUE TITLE
RHEL 8

### ISSUE THREAD

**Issue by jjdubs77** [NetAppDocs/bluexp-setup-admin#304]
### Page URL

https://docs.netapp.com/us-en/bluexp-setup-admin/task-install-connector-on-prem.html

### Page title

Install and set up a Connector on premises

### Summary

Please update RHEL 8 support. RHEL 7 is EOL June 2024.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-bcammett** [comment]
Hi @jjdubs77,

The team is working on updating our operating system support. I can't comment on the scope or timeline, but the release notes will be updated when changes are made available.

Because there's nothing for me to change in the documentation right now, I'm going to close out this issue.

Regards,
Ben
